server:
  profiles:
    active: dev
  port: 7777

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.241.139:3306/test?characterEncoding=UTF-8&useSSL=false
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.241.139:8848
  application:
    name: service-user