server:
  profiles:
    active: dev
  port: 7778

spring:
  application:
    name: service-order
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.241.139:3306/test?characterEncoding=UTF-8&useSSL=false
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.241.139:8848
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
